-- AlterTable
ALTER TABLE `PO_Request` MODIFY `reason` ENUM('OVERSTOCKING', 'EXPIRED', 'BAD_ORDER', 'OTHERS', 'KITCHEN_SUPPLY') NOT NULL,
    MODIFY `status` ENUM('PENDING', 'RETURNED') NOT NULL DEFAULT 'RETURNED';
